### ISSUE TITLE
Look at using Python stdlib stuff

### ISSUE THREAD

**Issue by msabramo** [rocky/pycolumnize#16]
Only in Python 3.3 and above, there is `shutil.get_terminal_size`:

https://docs.python.org/3/library/shutil.html#querying-the-size-of-the-output-terminal

The advantage of using this is that at least on Python >= 3.3, this would probably work on Windows. I doubt it works now because of the env variables and unix commands.

**Comment by rocky** [comment]
If you want to extend terminal_width() to check the Python version, do the
import inside the if test and use that, that'd be great.

**Comment by msabramo** [comment]
Ooh, look at what I found:

https://pypi.python.org/pypi/backports.shutil_get_terminal_size

**Comment by rocky** [comment]
Cool!

**Comment by msabramo** [comment]
Looks quite straightforward:

```pycon
In [1]: from backports.shutil_get_terminal_size import get_terminal_size

In [2]: get_terminal_size()
Out[2]: terminal_size(columns=176, lines=43)
```
