### ISSUE TITLE
Create README.rst for PyPI

### ISSUE THREAD

**Issue by msabramo** [rocky/pycolumnize#22]
PyPI will nicely format a reST document and doesn't support Markdown.

**Comment by rocky** [comment]
I think this does it. Please review and close if this is acceptable.

**Comment by msabramo** [comment]
Looks good. Want to do `python setup.py register` to update the description on PyPI?

**Comment by rocky** [comment]
Ok. [Version 0.3.8](https://pypi.python.org/pypi/columnize/0.3.8) is out. Dunno why version badge still says 0.3.7, I imagine it will right itself eventually.

**Comment by msabramo** [comment]
Cool! Thanks!

The version badge showing the old value I suspect is because GitHub does caching of images. I remember that when GitHub first rolled this out, it was kind of a big deal, because it broke Travis CI badges and such.
