### ISSUE TITLE
do not require mock

### ISSUE THREAD

**Issue by pgajdos** [rocky/pycolumnize#28]
Please consider to require unittest.mock instead.

**Comment by mcepl** [comment]
And this is the [patch](https://github.com/rocky/pycolumnize/files/8204868/python-columnize-no-mock.patch.txt) to do it.

**Comment by rocky** [comment]
Thanks for the patch. 

This code is quite old and goes back probably before unittest.mock. Although I use it every day via the trepan debugger, it's not something that has need change for the functional parts.

PR #24 also address this, but CI is failing. And there are a number of other things in the Python2 era program that could be modernized. 

So when I get a chance, I'll the code so it meets current fashion.

**Comment by rocky** [comment]
With release 0.3.11 mock is no longer used in modern Python (3.6-3.10) however in the older versions (which is in a separate git branch) it is still used as it is needed. 

But please double check.

**Comment by mcepl** [comment]
Same, looks perfect.

**Comment by rocky** [comment]
Great - thanks for checking. Closing then.
